version: '3.8'

services:
  db:
    image: postgres:15
    container_name: 
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: theloop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: recet
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
