FROM node:24-alpine AS base

FROM base AS workspace
RUN apk add --no-cache libc6-compat
RUN corepack enable pnpm

FROM workspace AS dependencies
WORKDIR /app
COPY ./apps/server .
RUN --mount=type=cache,target=/pnpm/store \
    pnpm install 

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 expressjs 

USER expressjs

CMD ["node", "src/index.js"]
