FROM node:24-alpine AS base


RUN apk add --no-cache libc6-compat

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable pnpm

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

WORKDIR /app

COPY --chown=nextjs:nodejs package.json pnpm-lock.yaml ./pnpm-workspace.yaml .
COPY --chown=nextjs:nodejs ./apps/client-web/package.json ./apps/client-web/package.json

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY --chown=nextjs:nodejs . .

USER nextjs
CMD ["pnpm", "dev:web"]
